language: cpp
compiler: gcc
sudo: require
dist: bionic

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt-5.11.1-bionic -y
  - sudo apt-get update -q
  - sudo apt-get install qt511base qt511multimedia -y
  - source /opt/qt511/bin/qt511-env.sh


install:
  - gcc --version
  - g++ --versio
  - sudo pip install --upgrade pip
  - sudo pip install six --upgrade
  - sudo pip install pip --upgrade
  - sudo pip install hazm
  - sudo apt-get install openssl -y
  - sudo apt-get install libgl1-mesa-dev -y
  - sudo apt-get install libespeak-ng-dev -y
  - sudo apt-get install libsamplerate0-dev -y

# Build steps
script:
  ## build Tihu
  - make ready
  - make build
  #- make test
  - make play
  ## For unknown reason returns: "undefined symbol src_new"
  ##- build/tihu_play build/libtihu.so "سلام" /tmp/raw1

  ## tihu console => appimage
  - cd ./tools/tihu_console
  - qmake CONFIG+=release PREFIX=/usr
  - make -j$(nproc)
## https://github.com/probonopd/linuxdeployqt/issues/338
  #- sudo apt-get update
  #- sudo apt-get -y install libgtk2.0-dev
  #- git clone http://code.qt.io/qt/qtstyleplugins.git
  #- cd qtstyleplugins
  #- qmake # be sure to use the one from the Qt installation you are using for the application
  #- make -j$(nproc)
  #- sudo make install
  #- cd -

  ## https://github.com/probonopd/linuxdeployqt/issues/340
  #- make INSTALL_ROOT=appdir -j$(nproc) install ; find appdir/
  #- wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
  #- chmod a+x linuxdeployqt-continuous-x86_64.AppImage
  #- unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
  #- ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop -appimage
  #- ls
  #- cp Tihu_console-*.AppImage ../../build
  - cp tihu_console ../../build

  ## tihu_server
  - cd -
  # installing gprc
  - git clone https://github.com/grpc/grpc
  - cd grpc
  - git checkout tags/v1.19.1
  - git submodule update --init
  - sed -i 's/-Werror/ /g' Makefile
  - make
  - sudo make install
  # protoc
  - cd third_party/protobuf
  - sudo apt-get install autoconf automake libtool curl make g++ unzip
  - git submodule update --init --recursive
  - ./autogen.sh
  - ./configure
  - make
  - sudo make install
  - sudo ldconfig
  # compile tihu_server
  - cd ../../..
  - cd tools/grpc
  - make tihu_server

  # to solve undefined_symbols (Unknown reason)
  - cp /usr/local/lib/libgrpc++.so.1 ../../build
  - cp /usr/local/lib/libgrpc++_reflection.so.1 ../../build
  - cp /usr/local/lib/libgrpc.so.7 ../../build

  ## pack everything
  - cd ../../build && tar -czf tihu-linux-x64.tar.gz *

deploy:
  provider: releases
  api_key:
    secure: $GITHUB_OAUTH_TOKEN
  file:
    - tihu-linux-x64.tar.gz
  skip_cleanup: true
  on:
    tags: true
